name = "notion-expense"
main = "worker.js"
compatibility_date = "2024-12-30"

[[d1_databases]]
binding = "DB"
database_name = "notion-expense-db"
database_id = "965d5c49-a8f9-4820-bc18-ac959924df84"

# Optional custom domain (uncomment after adding a zone to Cloudflare)
# [[routes]]
# pattern = "expense.yourdomain.com/*"
# zone_name = "yourdomain.com"

[env.stag]
name = "notion-expense-stag"

[[env.stag.d1_databases]]
binding = "DB"
database_name = "notion-expense-db"
database_id = "965d5c49-a8f9-4820-bc18-ac959924df84"
